default_context:
  project_name: 'postgres-fastapi'
  project_slug: 'vikings'
  domain_main: 'localhost'
  domain_staging: 'localhost'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'localhost'
  secret_key: 'Adobe$1234'
  first_superuser: 'tat32446'
  first_superuser_password: 'Adobe$1234'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.localhost, https://localhost, https://localhost, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@localhost'
  postgres_password: 'changethis'
  pgadmin_default_user: 'tat32446'
  pgadmin_default_user_password: 'Adobe$1234'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'localhost'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Adobe$1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
